version: "3"

services:

  symfony_app:
    build: .
    environment:
      SYMFONY_ENV: "$SYMFONY_ENV"
      SYMFONY__DATABASE_HOST: symfony_db
      SYMFONY__DATABASE_PORT: 3306
      SYMFONY__DATABASE_NAME: "$DATABASE_NAME"
      SYMFONY__DATABASE_USER: "$DATABASE_USER"
      SYMFONY__DATABASE_PASSWORD: "$DATABASE_PASSWORD"
      SYMFONY__ELASTICSEARCH_HOST: symfony_elasticsearch
      SYMFONY__ELASTICSEARCH_PORT: 9200
      SYMFONY__ELASTICSEARCH_INDEX_NAME: "$ELASTICSEARCH_INDEX_NAME"
    depends_on:
      - symfony_db
      - symfony_redis
      - symfony_mailcatcher
      - symfony_elasticsearch

  symfony_db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: "$DATABASE_NAME"
      MYSQL_USER: "$DATABASE_USER"
      MYSQL_PASSWORD: "$DATABASE_PASSWORD"

  symfony_redis:
    image: redis:3.0

  symfony_elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    environment:
      - "discovery.type=single-node"

  symfony_mailcatcher:
    image: schickling/mailcatcher

  symfony_adminer:
    image: adminer
